# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protonium/options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protonium/options.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\322G\002\010\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17protonium/options.proto\x1a google/protobuf/descriptor.proto\" \n\x0eServiceOptions\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1f\n\rMethodOptions\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1d\n\x0b\x46ileOptions\x12\x0e\n\x06ignore\x18\x01 \x01(\x08:L\n\x11protonium_service\x12\x1f.google.protobuf.ServiceOptions\x18\xfa\x08 \x01(\x0b\x32\x0f.ServiceOptions:I\n\x10protonium_method\x12\x1e.google.protobuf.MethodOptions\x18\xfa\x08 \x01(\x0b\x32\x0e.MethodOptions:C\n\x0eprotonium_file\x12\x1c.google.protobuf.FileOptions\x18\xfa\x08 \x01(\x0b\x32\x0c.FileOptionsB\x05\xd2G\x02\x08\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


PROTONIUM_SERVICE_FIELD_NUMBER = 1146
protonium_service = _descriptor.FieldDescriptor(
  name='protonium_service', full_name='protonium_service', index=0,
  number=1146, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
PROTONIUM_METHOD_FIELD_NUMBER = 1146
protonium_method = _descriptor.FieldDescriptor(
  name='protonium_method', full_name='protonium_method', index=1,
  number=1146, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
PROTONIUM_FILE_FIELD_NUMBER = 1146
protonium_file = _descriptor.FieldDescriptor(
  name='protonium_file', full_name='protonium_file', index=2,
  number=1146, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_SERVICEOPTIONS = _descriptor.Descriptor(
  name='ServiceOptions',
  full_name='ServiceOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='ServiceOptions.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=93,
)


_METHODOPTIONS = _descriptor.Descriptor(
  name='MethodOptions',
  full_name='MethodOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MethodOptions.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=126,
)


_FILEOPTIONS = _descriptor.Descriptor(
  name='FileOptions',
  full_name='FileOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ignore', full_name='FileOptions.ignore', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['ServiceOptions'] = _SERVICEOPTIONS
DESCRIPTOR.message_types_by_name['MethodOptions'] = _METHODOPTIONS
DESCRIPTOR.message_types_by_name['FileOptions'] = _FILEOPTIONS
DESCRIPTOR.extensions_by_name['protonium_service'] = protonium_service
DESCRIPTOR.extensions_by_name['protonium_method'] = protonium_method
DESCRIPTOR.extensions_by_name['protonium_file'] = protonium_file
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceOptions = _reflection.GeneratedProtocolMessageType('ServiceOptions', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEOPTIONS,
  '__module__' : 'protonium.options_pb2'
  # @@protoc_insertion_point(class_scope:ServiceOptions)
  })
_sym_db.RegisterMessage(ServiceOptions)

MethodOptions = _reflection.GeneratedProtocolMessageType('MethodOptions', (_message.Message,), {
  'DESCRIPTOR' : _METHODOPTIONS,
  '__module__' : 'protonium.options_pb2'
  # @@protoc_insertion_point(class_scope:MethodOptions)
  })
_sym_db.RegisterMessage(MethodOptions)

FileOptions = _reflection.GeneratedProtocolMessageType('FileOptions', (_message.Message,), {
  'DESCRIPTOR' : _FILEOPTIONS,
  '__module__' : 'protonium.options_pb2'
  # @@protoc_insertion_point(class_scope:FileOptions)
  })
_sym_db.RegisterMessage(FileOptions)

protonium_service.message_type = _SERVICEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(protonium_service)
protonium_method.message_type = _METHODOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(protonium_method)
protonium_file.message_type = _FILEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(protonium_file)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
